add certificates to test

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -32,6 +32,20 @@ script:
     -e truststore_owner=travis
     -e truststore_group=travis
 
+  # there should be 3 certificates in the trust store now
+  - >
+    echo {{ truststore_password }} | keytool -keystore {{ truststore_path }}
+    | grep -q "Your keystore contains 3 entries"
+    && (echo 'three certs test: pass' && exit 0)
+    || (echo 'three certs test: fail' && exit 1)
+
+  # check how this goes...
+  - >
+    echo {{ truststore_password }} | keytool -keystore {{ truststore_path }}
+    | grep -q "Your keystore contains 2 entries"
+    && (echo 'two certs test: pass' && exit 0)
+    || (echo 'two certs test: fail' && exit 1)
+
   # this should do nothing
   - >
     ansible-playbook tests/test.yml -i tests/inventory --connection=local
